# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Tatiana Gaponova
description:      'CINEMA | AI | TRAVEL'
url:              http://baroquerock.github.io
base.url:         nil

paginate:         5

# Custom vars

github:
  repo:           https://github.com/baroquerock/baroquerock.github.io


plugins: [jekyll-gist, jekyll-archives, jekyll-paginate]
