# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Tatiana Gaponova
description:      'XXX &middot; YYY &middot; ZZZ'
url:              http://baroquerock.github.io
base.url:         nil

paginate:         1

# Custom vars

github:
  repo:           https://github.com/baroquerock/baroquerock.github.io


plugins: [jekyll-gist, jekyll-archives, jekyll-paginate]
