# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Tatiana Gaponova
description:      'CINEMA | AI | TRAVEL'
url:              http://baroquerock.github.io
baseurl:          /

paginate:         5

# Custom vars

github:
  repo:           https://github.com/baroquerock/baroquerock.github.io

pages_list:
  Feed: '/atom.xml'

plugins: [jekyll-gist, jekyll-archives, jekyll-paginate]
