# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            x
tagline:          'y'
description:      'z'
url:              http://baroquerock.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars

github:
  repo:           https://github.com/baroquerock/baroquerock.github.io

gems: [jekyll-gist]
