# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Tatiana Gaponova
tagline:          'y'
description:      'cinema | ai | travel'
url:              http://baroquerock.github.io
baseurl:          /

paginate:         5

# Custom vars

github:
  repo:           https://github.com/baroquerock/baroquerock.github.io

pages_list:
  Feed: '/atom.xml'

gems: [jekyll-gist, jekyll-archives]
